version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - project
  
  graphql-engine:
    image: hasura/graphql-engine:v1.3.2
    ports:
      - ${HASURA_PORT}:${HASURA_PORT}"
    depends_on:
      - "postgres"
    restart: always
    tty: true
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/$SCHEMA
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    networks:
      - project
  
  front:
    image: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    environment:
      SCHEMA: $SCHEMA
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    tty: true
    volumes:
      - ./front:/front
    networks:
      - project

  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      SCHEMA: $SCHEMA
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    restart: always
    tty: true
    volumes:
      - ./api:/api
    networks:
      - project
    command: uvicorn app:app --reload --host 0.0.0.0 --port $API_PORT

volumes:
  db_data:

networks:
  project:
    driver: bridge